# Generated by Django 5.2.4 on 2025-07-12 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jewel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("обеци", "ОБЕЦИ"),
                            ("гривна", "ГРИВНА"),
                            ("пръстен", "ПРЪСТЕН"),
                            ("огърлица", "ОГЪРЛИЦА"),
                            ("висулка", "ВИСУЛКА"),
                            ("ланец", "ЛАНЕЦ"),
                            ("верига_за_панталон", "ВЕРИГА_ЗА_ПАНТАЛОН"),
                            ("верига_за_тяло", "ВЕРИГА_ЗА_ТЯЛО"),
                            ("връзка_за_очила", "ВРЪЗКА_ЗА_ОЧИЛА"),
                            ("гривна_за_глезен", "ГРИВНА_ЗА_ГЛЕЗЕН"),
                            ("броеница", "БРОЕНИЦА"),
                            ("колан", "КОЛАН"),
                            ("бижу_за_коса", "БИЖУ_ЗА_КОСА"),
                            ("ключодържател", "КЛЮЧОДЪРЖАТЕЛ"),
                            ("брошка", "БРОШКА"),
                            ("книгоразделител", "КНИГОРАЗДЕЛИТЕЛ"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "chain_weave",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("weight", models.PositiveIntegerField(blank=True, null=True)),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
