# Generated by Django 5.2.4 on 2025-07-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("square", "SQUARE"),
                            ("rectangle", "RECTANGLE"),
                            ("circle", "CIRCLE"),
                            ("oval", "OVAL"),
                            ("other", "OTHER"),
                        ]
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=3, max_digits=5)),
                ("jewel", models.ManyToManyField(to="jewels.jewel")),
            ],
        ),
        migrations.CreateModel(
            name="Metal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=5)),
                ("jewel", models.ManyToManyField(to="jewels.jewel")),
            ],
        ),
    ]
