# Generated by Django 5.2.4 on 2025-07-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0002_gem_metal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewel",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jewel",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
    ]
