# Generated by Django 5.2.4 on 2025-07-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0003_alter_jewel_length_alter_jewel_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=5)),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
