# Generated by Django 5.2.4 on 2025-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0004_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jewel",
            name="chain_weave",
        ),
        migrations.AddField(
            model_name="jewel",
            name="color",
            field=models.CharField(
                choices=[
                    ("square", "SQUARE"),
                    ("rectangle", "RECTANGLE"),
                    ("circle", "CIRCLE"),
                    ("oval", "OVAL"),
                    ("other", "OTHER"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jewel",
            name="weave_technique",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
