# Generated by Django 5.2.4 on 2025-07-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0005_remove_jewel_chain_weave_jewel_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewel",
            name="color",
            field=models.CharField(
                choices=[
                    ("green", "GREEN"),
                    ("dark green", "DARK GREEN"),
                    ("light green", "LIGHT GREEN"),
                    ("red", "RED"),
                    ("dark red", "DARK RED"),
                    ("cherry", "CHERRY"),
                    ("white", "WHITE"),
                    ("gray", "GRAY"),
                    ("graphite_gray", "GRAPHITE_GRAY"),
                    ("yellow", "YELLOW"),
                    ("golden", "GOLDEN"),
                    ("coffee", "COFFEE"),
                    ("brown", "BROWN"),
                    ("black", "BLACK"),
                    ("light_brown", "LIGHT_BROWN"),
                    ("purple", "PURPLE"),
                    ("multicolor", "MULTICOLOR"),
                    ("orange", "ORANGE"),
                    ("rose", "ROSE"),
                    ("blue", "BLUE"),
                    ("light_blue", "LIGHT_BLUE"),
                    ("dark_blue", "DARK_BLUE"),
                    ("steel_silver", "STEEL_SILVER"),
                    ("other", "OTHER"),
                ],
                default="other",
            ),
        ),
        migrations.AlterField(
            model_name="jewel",
            name="type",
            field=models.CharField(
                choices=[
                    ("earrings", "EARRINGS"),
                    ("bracelet", "BRACELET"),
                    ("ring", "RING"),
                    ("necklace", "NECKLACE"),
                    ("pendant", "PENDANT"),
                    ("chain", "CHAIN"),
                    ("trousers_chain", "TROUSERS_CHAIN"),
                    ("body_chain", "BODY_CHAIN"),
                    ("eyeglass", "EYEGLASS_CORD"),
                    ("anklet", "ANKLET"),
                    ("beaded_necklace", "BEADED_NECKLACE"),
                    ("belt", "BELT"),
                    ("heart_pin", "HAIRPIN"),
                    ("keychain", "KEYCHAIN"),
                    ("brooch", "BROOCH"),
                    ("bookmark", "BOOKMARK"),
                ],
                max_length=50,
            ),
        ),
    ]
