# Generated by Django 5.2.4 on 2025-07-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0006_alter_jewel_color_alter_jewel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewel",
            name="type",
            field=models.CharField(
                choices=[
                    ("earrings", "EARRINGS"),
                    ("bracelet", "BRACELET"),
                    ("ring", "RING"),
                    ("necklace", "NECKLACE"),
                    ("pendant", "PENDANT"),
                    ("chain", "CHAIN"),
                    ("trousers_chain", "TROUSERS_CHAIN"),
                    ("body_chain", "BODY_CHAIN"),
                    ("eyeglass", "EYEGLASS_CORD"),
                    ("anklet", "ANKLET"),
                    ("beaded_necklace", "BEADED_NECKLACE"),
                    ("belt", "BELT"),
                    ("heart_pin", "HAIRPIN"),
                    ("keychain", "KEYCHAIN"),
                    ("brooch", "BROOCH"),
                    ("bookmark", "BOOKMARK"),
                    ("other", "OTHER"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
