# Generated by Django 5.2.4 on 2025-07-18 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0007_alter_jewel_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("earrings", "EARRINGS"),
                            ("bracelet", "BRACELET"),
                            ("ring", "RING"),
                            ("necklace", "NECKLACE"),
                            ("pendant", "PENDANT"),
                            ("chain", "CHAIN"),
                            ("trousers_chain", "TROUSERS_CHAIN"),
                            ("body_chain", "BODY_CHAIN"),
                            ("eyeglass", "EYEGLASS_CORD"),
                            ("anklet", "ANKLET"),
                            ("beaded_necklace", "BEADED_NECKLACE"),
                            ("belt", "BELT"),
                            ("heart_pin", "HAIRPIN"),
                            ("keychain", "KEYCHAIN"),
                            ("brooch", "BROOCH"),
                            ("bookmark", "BOOKMARK"),
                            ("other", "OTHER"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="jewel",
            name="color",
        ),
        migrations.RemoveField(
            model_name="jewel",
            name="type",
        ),
        migrations.AddField(
            model_name="gem",
            name="color",
            field=models.CharField(
                choices=[
                    ("green", "GREEN"),
                    ("dark green", "DARK GREEN"),
                    ("light green", "LIGHT GREEN"),
                    ("red", "RED"),
                    ("dark red", "DARK RED"),
                    ("cherry", "CHERRY"),
                    ("white", "WHITE"),
                    ("gray", "GRAY"),
                    ("graphite_gray", "GRAPHITE_GRAY"),
                    ("yellow", "YELLOW"),
                    ("golden", "GOLDEN"),
                    ("coffee", "COFFEE"),
                    ("brown", "BROWN"),
                    ("black", "BLACK"),
                    ("light_brown", "LIGHT_BROWN"),
                    ("purple", "PURPLE"),
                    ("multicolor", "MULTICOLOR"),
                    ("orange", "ORANGE"),
                    ("rose", "ROSE"),
                    ("blue", "BLUE"),
                    ("light_blue", "LIGHT_BLUE"),
                    ("dark_blue", "DARK_BLUE"),
                    ("steel_silver", "STEEL_SILVER"),
                    ("other", "OTHER"),
                ],
                default="other",
            ),
        ),
        migrations.AlterField(
            model_name="metal",
            name="jewel",
            field=models.ManyToManyField(related_name="metals", to="jewels.jewel"),
        ),
        migrations.AddField(
            model_name="jewel",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="jewels.category",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
                (
                    "jewels",
                    models.ManyToManyField(
                        related_name="collections", to="jewels.jewel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/photos/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("is_admin_uploaded", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jewels.category",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jewels.collection",
                    ),
                ),
                (
                    "jewel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jewels.jewel",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
