# Generated by Django 5.2.4 on 2025-07-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0008_category_remove_jewel_color_remove_jewel_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("earrings", "EARRINGS"),
                    ("bracelet", "BRACELET"),
                    ("ring", "RING"),
                    ("necklace", "NECKLACE"),
                    ("pendant", "PENDANT"),
                    ("chain", "CHAIN"),
                    ("trousers_chain", "TROUSERS_CHAIN"),
                    ("body_chain", "BODY_CHAIN"),
                    ("eyeglass", "EYEGLASS_CORD"),
                    ("anklet", "ANKLET"),
                    ("beaded_necklace", "BEADED_NECKLACE"),
                    ("belt", "BELT"),
                    ("heart_pin", "HAIRPIN"),
                    ("keychain", "KEYCHAIN"),
                    ("brooch", "BROOCH"),
                    ("bookmark", "BOOKMARK"),
                    ("other", "OTHER"),
                ]
            ),
        ),
    ]
