# Generated by Django 5.2.4 on 2025-07-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0009_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
