# Generated by Django 5.2.4 on 2025-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0010_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
