# Generated by Django 5.2.4 on 2025-09-01 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0012_alter_photo_category_alter_photo_collection_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JewelSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("value", models.TextField(max_length=1500)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="JewelTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("body_en", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="jewel",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="jewel",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="jewel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jewel",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jewel",
            name="long_description_en",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name="jewel",
            name="rating_avg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="jewel",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jewel",
            name="short_description_en",
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="jewel",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="jewel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="material",
            name="jewel",
            field=models.ManyToManyField(related_name="materials", to="jewels.jewel"),
        ),
        migrations.AddField(
            model_name="photo",
            name="is_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photo",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="gem",
            name="jewel",
            field=models.ManyToManyField(related_name="gems", to="jewels.jewel"),
        ),
        migrations.AlterField(
            model_name="gem",
            name="type",
            field=models.CharField(
                choices=[
                    ("apatite", "APATITE"),
                    ("white_howlite", "WHITE HOWLITE"),
                    ("green_aventurine", "GREEN AVENTURINE"),
                    ("kyanite", "KYANITE"),
                    ("corundum", "CORUNDUM"),
                    ("prehnite", "PREHNITE"),
                    ("rhyolite", "RHYOLITE"),
                    ("red_jadeite", "RED JADEITE"),
                    ("black_tourmaline", "BLACK TOURMALINE"),
                    ("strawberry_quartz", "STRAWBERRY QUARTZ"),
                    ("jasper", "JASPER"),
                    ("aventurine", "AVENTURINE"),
                    ("amethyst", "AMETHYST"),
                    ("agate", "AGATE"),
                    ("garnet", "GARNET"),
                    ("jadeite", "JADEITE"),
                    ("cats_eye", "CAT'S EYE"),
                    ("moonstone", "MOONSTONE"),
                    ("malachite", "MALACHITE"),
                    ("moss_agate", "MOSS AGATE"),
                    ("onyx", "ONYX"),
                    ("peridot", "PERIDOT"),
                    ("rose_quartz", "ROSE QUARTZ"),
                    ("sapphire", "SAPPHIRE"),
                    ("mother_of_pearl", "MOTHER OF PEARL"),
                    ("turquoise", "TURQUOISE"),
                    ("unakite", "UNAKITE"),
                    ("hematite", "HEMATITE"),
                    ("howlite", "HOWLITE"),
                    ("cherry_quartz", "CHERRY QUARTZ"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="type",
            field=models.CharField(
                choices=[
                    ("epoxy", "EPOXY"),
                    ("wood", "WOOD"),
                    ("enamel", "ENAMEL"),
                    ("leather", "LEATHER"),
                    ("glass_beads", "GLASS_BEADS"),
                    ("japanese_toho_beads", "JAPANESE_TOHO_BEAD"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="metal",
            name="type",
            field=models.CharField(
                choices=[
                    ("medical_steel_316l", "MEDICAL_STEEL_316L"),
                    ("stainless_steel", "STAINLESS_STEEL"),
                    ("silver", "SILVER"),
                    ("gold", "GOLD"),
                    ("platinum", "PLATINUM"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("jewel",),
                name="one_cover_photo_per_jewel",
            ),
        ),
        migrations.AddField(
            model_name="jewelspec",
            name="jewel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specs",
                to="jewels.jewel",
            ),
        ),
        migrations.AddField(
            model_name="jeweltab",
            name="jewel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tabs",
                to="jewels.jewel",
            ),
        ),
    ]
