# Generated by Django 5.2.4 on 2025-09-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0013_jewelspec_jeweltab_alter_jewel_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jewel",
            old_name="long_description_en",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="jewel",
            old_name="short_description_en",
            new_name="short_description",
        ),
    ]
