# Generated by Django 5.2.4 on 2025-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0014_rename_long_description_en_jewel_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelspec",
            name="label",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
