# Generated by Django 5.2.4 on 2025-09-02 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0015_alter_jewelspec_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JewelSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, null=True, unique=True
                    ),
                ),
                ("short_description", models.TextField(blank=True, max_length=250)),
                ("long_description", models.TextField(blank=True, max_length=1500)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="JewelSetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="rating_avg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="collection",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="sets",
            field=models.ManyToManyField(
                blank=True, related_name="collections", to="jewels.jewelset"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="jewel_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="jewels.jewelset",
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("collection",),
                name="one_cover_photo_per_collection",
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("category",),
                name="one_cover_photo_per_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("jewel_set",),
                name="one_cover_photo_per_jewel_set",
            ),
        ),
        migrations.AddField(
            model_name="jewelsetitem",
            name="jewel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="set_items",
                to="jewels.jewel",
            ),
        ),
        migrations.AddField(
            model_name="jewelsetitem",
            name="jewel_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="jewels.jewelset",
            ),
        ),
        migrations.AddField(
            model_name="jewelset",
            name="jewels",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_sets",
                through="jewels.JewelSetItem",
                to="jewels.jewel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jewelsetitem",
            unique_together={("jewel_set", "jewel")},
        ),
    ]
