# Generated by Django 5.2.4 on 2025-09-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewels", "0016_jewelset_jewelsetitem_collection_rating_avg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewel",
            name="rating_avg",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=3
            ),
        ),
    ]
