# Generated by Django 5.2.4 on 2025-09-10 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_likeditem"),
        ("jewels", "0017_alter_jewel_rating_avg"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="likeditem",
            name="uniq_user_jewel_like",
        ),
        migrations.AddField(
            model_name="likeditem",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="likeditem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="likeditem",
            index=models.Index(
                fields=["session_key", "jewel"], name="common_like_session_1f1714_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="likeditem",
            index=models.Index(
                fields=["-created_at"], name="common_like_created_32343a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="likeditem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "jewel"),
                name="uniq_user_jewel_like",
            ),
        ),
        migrations.AddConstraint(
            model_name="likeditem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key", ""), _negated=True),
                fields=("session_key", "jewel"),
                name="uniq_session_jewel_like",
            ),
        ),
    ]
