# Generated by Django 5.2.4 on 2025-09-03 23:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
                sql=
                """
                    CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS auth_user_email_ci_unique
                    ON auth_user (LOWER(email));
                """,
            reverse_sql="""
                    DROP INDEX CONCURRENTLY IF EXISTS auth_user_email_ci_unique;
                """,
        ),
    ]
